<?xml version="1.0" encoding="utf-8"?><Database Name="users" Class="databaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=e:\e\university\web\trunk\XSLT\WebApp\WebApp\App_Data\users.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="DomainModel.Properties.Settings" SettingsPropertyName="usersConnectionString3" Provider="System.Data.SqlClient" />
  <Table Name="dbo.UsersData" Member="UsersDatas">
    <Type Name="UsersData">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>